--- 
title: "Data analysis and R programming"
author: "Laurent Gatto"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
description: "Material for the 'Data analysis and R programming' course."
github-repo: lgatto/2017_11_09_Rcourse_Jena
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
source("./src/setup.R")
```

# Introduction

This course presents a 2-day introduction to data analysis and
visualisation with R as well as certain programming topics. It is
formatted as a `bookdown` document

The material can be accessed here: 

- https://lgatto.github.io/2017_11_09_Rcourse_Jena/

The source code for this document is available on GitHub at

- https://github.com/lgatto/2017_11_09_Rcourse_Jena.

## Installation

We will install required packages as we go along. Before the course,
participants should install a recent version of
[R](https://www.r-project.org/) (ideally the current release version)
and [RStudio](https://www.rstudio.com/products/RStudio/), or any other
editor of their choice.

## Programme

- Morning: 9:30 - 13:00 (3 hours, with 30 min break)
- Afternoon: 14:00 - 17:00 (3 hours, with a shorter break)

#### Day 1  {-}

- Setup and introduction

> The following material is based on Data Carpentry's the
> [Data analisis and visualisation](http://www.datacarpentry.org/R-ecology-lesson/) lessons.

- Spreadsheets and tidy data (1 hour)
- Data manipulation using the tidyverse (1.5 hours)
- Visualisation with ggplot2 (1.5 hours)
- Reproducible research with Rmarkdown (0.5 hour)
- Wrap-up

#### Day 2 {-}
- R package development (about 1.5 hours)
- Viz. of high-dimensional data (bit.ly/highdimvis) (1.5 hours)
- Interactive visualisation: ggvis, shiny (1.5 hours)
- Navigate and mine Bioconductor for useful scripting components (0.5 hour)
- Wrap-up


## License and credits

This material is licensed under the
[Creative Commons Attribution-ShareAlike 3.0 License](http://creativecommons.org/licenses/by-sa/3.0/). 

Some content is inspired by other sources, see the first paragraph in
the respective chapters for credits.

